databases:
  - name: search_product-postgres
    databaseName: search_product
    plan: free
    user: search_product

services:
  - type: redis
    name: search_product-redis
    plan: free
    ipAllowList: [] # only allow internal connections

  - type: web
    name: search_product
    plan: free
    runtime: python
    buildCommand: "./render_build.sh"
    startCommand: "poetry run gunicorn search_product.wsgi:application --chdir backend --limit-request-line 8188 --log-file -"
    envVars:
      - key: ENABLE_DJANGO_COLLECTSTATIC
        value: 1
      - key: AUTO_MIGRATE
        value: 1
      - key: DATABASE_URL
        fromDatabase:
          name: search_product-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: search_product-redis
          property: connectionString
      - fromGroup: python-services
      - fromGroup: integrations-credentials

  # As there aren't free plans for Workers in Render, the configuration for
  # celery workers/beat will be commented by default
  #
  # - type: worker
  #   name: worker-default
  #   runtime: python
  #   env: python
  #   buildCommand: poetry install
  #   startCommand: "poetry run celery --workdir backend --app=search_product worker --loglevel=info --max-memory-per-child=$WORKER_MAX_MEMORY  --concurrency=$WORKER_CONCURRENCY"
  #   envVars:
  #     - key: REMAP_SIGTERM
  #       value: SIGQUIT
  #     - key: WORKER_MAX_MEMORY
  #       sync: false
  #     - key: WORKER_CONCURRENCY
  #       sync: false
  #     - key: DATABASE_URL
  #       fromDatabase:
  #         name: search_product-postgres
  #         property: connectionString
  #     - key: REDIS_URL
  #       fromService:
  #         type: redis
  #         name: search_product-redis
  #         property: connectionString
  #     - fromGroup: python-services
  #     - fromGroup: integrations-credentials
  # - type: worker
  #   name: beat
  #   runtime: python
  #   env: python
  #   buildCommand: poetry install
  #   startCommand: "poetry run celery --workdir backend --app=search_product beat --loglevel=info"
  #   envVars:
  #     - key: REMAP_SIGTERM
  #       value: SIGQUIT
  #     - key: DATABASE_URL
  #       fromDatabase:
  #         name: search_product-postgres
  #         property: connectionString
  #     - key: REDIS_URL
  #       fromService:
  #         type: redis
  #         name: search_product-redis
  #         property: connectionString
  #     - fromGroup: python-services
  #     - fromGroup: integrations-credentials

envVarGroups:
  - name: python-services
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: POETRY_VERSION
        value: 1.7.1
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: search_product.settings.production
      - key: ALLOWED_HOSTS
        value: '*'
  - name: integrations-credentials
    envVars:
      - key: SENDGRID_USERNAME
        value: apikey
      - key: SENDGRID_PASSWORD
        value: placeholder-value
